package com.ex.model;

import java.awt.image.BufferedImage;
import java.time.LocalDateTime;

/**
 * @author that-team
 * This class defines an item. An item can be placed as a geocache by a user and then
 * retrieved by other users. We anticipate that many items will be picked up and placed
 * into the world again, as is customary in the geocaching scene.
 *
 * @param itemID -  a unique, identifying number for the item, generated by the Database
 * @param name - user defines the name to be displayed for the item
 * @param description - user may write a short description of the item and how to find it
 * @param date - this date refers to the last time this item was touched, either when it was
 *             placed or when it was retrieved
 * @param image - a picture of where the item is located, uploaded by the user who places it,
 *              intended to assist other users when looking for it
 * @param gpsLocation - JSON data including the longitude and latitude of the item's location
 * @param difficulty - a ranking, set by the user who places the item. The difficulty ranking
 *                   will inform other users how hard it will be to find. It will also be used
 *                   so that a user may filter geocaches near them, and it will be used for users
 *                   to gain experience by finding the item or placing it.
 *
 */

public class Item {
    private int itemID;
    private String name;
    private String description;
    private LocalDateTime date;
    private BufferedImage image;
    private String gpsLocation;
    private DifficultyLevel difficulty;

    public Item(){}

    public Item(String name, String description, LocalDateTime date, BufferedImage image, String gpsLocation, DifficultyLevel difficultyLevel) {
        this.name = name;
        this.description = description;
        this.date = date;
        this.image = image;
        this.gpsLocation = gpsLocation;
        this.difficulty = difficultyLevel;
    }

    public int getItemID() {
        return itemID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public LocalDateTime getDate() {
        return date;
    }

    public void setDate(LocalDateTime date) {
        this.date = date;
    }

    public BufferedImage getImage() {
        return image;
    }

    public void setImage(BufferedImage image) {
        this.image = image;
    }

    public String getGpsLocation() {
        return gpsLocation;
    }

    public void setGpsLocation(String gpsLocation) {
        this.gpsLocation = gpsLocation;
    }

    public DifficultyLevel getDifficultyLevel() {
        return difficulty;
    }

    public void setDifficultyLevel(DifficultyLevel difficultyLevel) {
        this.difficulty = difficultyLevel;
    }
}
