apiVersion: v1
kind: Pod
metadata:
  name: simplepod
  labels:
    app: testapp

spec:
  containers:
    - name: simplepod-cont
      image: walldiv/testk8s:v1.0
      ports:
        - containerPort: 8080
