apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
    - name: redis
      image: redis:5.0.4
      command:
        -redis-server
        -"/redis-master/redis.conf"
      env:
        - name: REDIS_HOST
          value: redis-clusterip
        - name: REDIS_PORT
          value: "6379"
        - name: MASTER
          value: "true";
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: ".01"
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: redis-config
            items:
              - key: redis-config
                path: redis.config

