package com.ex.model;

import java.awt.image.BufferedImage;
import java.time.LocalDateTime;

/**
 * @author that-team
 * This class defines a geocache location. An item can be placed into a geocache by a user and then
 * retrieved by other users. We anticipate that many items will be picked up and placed
 * into the world again, as is customary in the geocaching scene. We also anticipate that the same
 * geocache location will be reused, as is also customary.
 *
 * @param cacheID -  a unique, identifying number for the item, generated by the Database
 * @param name - user defines the name to be displayed for the geocache
 * @param description - user may write a short description about how to find the geocache
 * @param date - this date refers to the last time geocache was touched, either when it was
 *             placed or when something was retrieved from it
 * @param image - a picture of where the geocache is located, uploaded by the user who places it,
 *              intended to assist other users when looking for it, this field contains a URL linking
 *              to the storage location
 * @param gpsLocation - JSON data including the longitude and latitude of the geocache's location
 * @param difficulty - a ranking, set by the user who places the item. The difficulty ranking
 *                   will inform other users how hard it will be to find. It will also be used
 *                   so that a user may filter geocaches near them, and it will be used for users
 *                   to gain experience by finding the item or placing it.
 *
 */

public class Geocache {
    private int cacheID;
    private String name;
    private String description;
    private LocalDateTime date;
    private String image;
    private String gpsLocation;
    private DifficultyLevel difficulty;

    public Geocache(){}

    public Geocache(String name, String description, LocalDateTime date, String image, String gpsLocation, DifficultyLevel difficultyLevel) {
        this.name = name;
        this.description = description;
        this.date = date;
        this.image = image;
        this.gpsLocation = gpsLocation;
        this.difficulty = difficultyLevel;
    }

    public int getItemID() {
        return cacheID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public LocalDateTime getDate() {
        return date;
    }

    public void setDate(LocalDateTime date) {
        this.date = date;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getGpsLocation() {
        return gpsLocation;
    }

    public void setGpsLocation(String gpsLocation) {
        this.gpsLocation = gpsLocation;
    }

    public DifficultyLevel getDifficultyLevel() {
        return difficulty;
    }

    public void setDifficultyLevel(DifficultyLevel difficultyLevel) {
        this.difficulty = difficultyLevel;
    }
}
