apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
    app: myapp

spec:
  containers:
    - name: simple-pod-container
      image: ajduet/hello-dep
      ports:
        - containerPort: 8080
