pipeline {
   agent any

   stages {
      stage('WAR Generation') {
         steps {
		    withMaven(maven : 'mvn'){
			sh 'mvn clean package'
		    }
        }
      }
      stage('Docker Image Build'){
	    steps {
			sh 'docker build . -t cm:v0'
	    }
      }
      stage('Docker Hub Image Push'){
	    steps {
			sh 'docker tag cm:v0 jeanaldoph/voldemort:cm'
			sh 'docker push jeanaldoph/voldemort:cm'
		}
	  }
    }
}