kind: Deployment
apiVersion: apps/v1
metadata:
  name: users-deployment
  labels:
    app: users-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ThatTeam_Users-webapp
  template:
    metadata:
      labels:
        app: ThatTeam_Users-webapp
    spec:
      containers:
        - name: webapp
          image: walldiv/project2_users
          ports:
            - containerPort: 8080
