pipeline {
    agent any

    stages {
        stage('WAR Generation') {
            steps {
		        withMaven(maven : 'mvn'){
			        sh 'mvn clean package -f Coaster_customer/pom.xml'
		        }
            }
        }
        stage('Build Image'){
            steps{
                docker build Coaster_customer/. -t cc:v0
            }
        }
        stage('Push Image'){
            steps{
                docker tag cc:v0 jeanaldoph/voldemort:cc
                docker push jeanaldoph/voldemort:cc
            }
        }
    }
}
