pipeline {
    agent any

    stages {
        stage('WAR Generation') {
            steps {
		        withMaven(maven : 'mvn'){
			        sh 'mvn clean package -f Coaster_customer/pom.xml'
		        }
            }
        }
        stage('Build Image'){
            steps{
                sh 'docker build Coaster_customer/. -t cc:v0'
            }
        }
        stage('Push Image'){
            steps{
                sh 'docker tag cc:v0 jeanaldoph/voldemort:cc'
                sh 'docker push jeanaldoph/voldemort:cc'
            }
        }
    }
}
